### ISSUE TITLE
Too many parts for large objects upload

### ISSUE THREAD

**Issue by AdrienBigot** [polius/intelligent-s3-upload#1]
Hello,

First, many thanks for your work on this application that frankly save many time for my uploads !

I ran into a bug for big files that generate many parts. I got this error of the s3api : 
"Part number must be an integer between 1 and 10000"

Here my upload attempt  cutting my file in  10245928236 parts ? (I think there is also a bug here while calculating number of parts)

+==================================================================+
‖  Intelligent S3 Upload                                           ‖
+==================================================================+
- Scanning files...
- Starting the upload process...
[0.00%] [76.34 GB] 2016.tar.gpg (0.00%) [Part 10001/10245928236]
[Attempt 1/3] Multipart upload process failed. Retrying in 5 seconds...
[0.00%] [76.34 GB] 2016.tar.gpg (0.00%) [Part 10001/10245928236]
[Attempt 2/3] Multipart upload process failed. Retrying in 5 seconds...
[0.00%] [76.34 GB] 2016.tar.gpg (0.00%) [Part 10001/10245928236]
[Attempt 3/3] Multipart upload process failed. Retrying in 5 seconds...
- Multipart upload process failed after 3 attempts.
Error: An error occurred (InvalidArgument) when calling the UploadPart operation: Part number must be an integer between 1 and 10000, inclusive
- Overall Time: 0:10:05.450184

I'll try to debug as soon as I have the time, but I submit this issue to avoid forgetting :)

Regards,

Adrien

**Comment by polius** [comment]
Hi @adbig ,

Sorry for my very late response (after 2 years). I have accepted your [pull request](https://github.com/polius/intelligent-s3-upload/pull/2).

Have a nice day!
